# -*- coding: utf-8 -*-
"""Catalogo declarativo de fontes do diagnostico (ARQUITETURA.md §3.1).

Preenchido a partir de docs/diagnostico-plano-diretor/fontes-detalhe.md (T-007).
Fase A: fontes WFS + basemap. As fontes ArcGIS REST entram na T-012.

Cada fonte e um dict:
  id, eixo, nome, protocolo ("wfs"|"arcgis"|"geobr"|"osm"|"arquivo"|"basemap"|"ibge_tabular"|"zip_remoto"|"raster_cog"),
  endpoint, type_name, srs, filtro, licenca.
filtro: {"tipo": "cql_codigo", "campo": <str>}  -> CQL campo = <code_muni>
        {"tipo": "cql_nome",   "campo": <str>}  -> CQL campo = '<nome_muni>'
        {"tipo": "bbox"}                          -> filtro espacial por bbox
type_name pode conter "{uf}" (substituido pela sigla da UF do municipio).

Protocolo "ibge_tabular": dados tabulares do IBGE (PAM e Censo Agropecuário)
servidos pela API v3 de Agregados. Chaves: agregado, variaveis, classificacao,
periodo_default.

Protocolo "arquivo" (download manual): fontes oficiais que so existem atras
de login (ex.: gov.br) NAO tem endpoint — o conector procura um arquivo ja
baixado pelo usuario na pasta de downloads manuais (chave QSettings
"gisbr/pasta_downloads_manuais", default Downloads do sistema). Chaves:
  arquivo_glob: lista de globs (ex.: ["*sigef*.zip"]) — casa sem sensibilidade
                a caixa; vence o arquivo de st_mtime mais alto
  origem_url:   URL do portal de origem (vai no aviso quando o arquivo falta)
  requer_login: qual credencial o portal exige (informativo, ex.: "gov.br")

Protocolo "osm": fontes servidas pela API Overpass (host fixo no conector,
sem endpoint por fonte). O motor de diagnostico despacha por id para o
pipeline dedicado — "osm_vias" (vias/nós) e "osm_pois" (pontos de interesse).
Sem host próprio, ficam fora do tools/check_sources_tls.py.
"""

SOURCES = [
    # --- Eixo 1: Transportes ---
    {"id": "dnit_snv", "eixo": "transportes", "nome": "DNIT — SNV (rodovias federais)",
     "protocolo": "wfs", "endpoint": "https://geoservicos.inde.gov.br/geoserver/DNIT/ows",
     "type_name": "DNIT:snv_202507a", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "minfra_ferrovias", "eixo": "transportes", "nome": "MInfra — Ferrovias",
     "protocolo": "wfs", "endpoint": "https://geoservicos.inde.gov.br/geoserver/ows",
     "type_name": "MInfra:Ferrovias", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_nome", "campo": "municipio"}, "licenca": "Publica"},
    {"id": "der_mg_rodovias", "eixo": "transportes", "nome": "DER-MG — Rodovias estaduais",
     "protocolo": "wfs", "endpoint": "https://geoserver.meioambiente.mg.gov.br/IDE/wfs",
     "type_name": "IDE:ide_0401_mg_rodovias_lin", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bc250_rodovias", "eixo": "transportes", "nome": "IBGE — BC250 Trecho rodoviario",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CCAR:BC250_2025_rod_trecho_rodoviario_l", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bc250_ferrovias", "eixo": "transportes", "nome": "IBGE — BC250 Trecho ferroviario",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CCAR:BC250_2025_fer_trecho_ferroviario_l", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "osm_vias", "eixo": "transportes", "nome": "OSM — Vias urbanas (Overpass)",
     "protocolo": "osm", "licenca": "OpenStreetMap contributors"},
    # --- Eixo 2: Drenagem e Saneamento ---
    {"id": "sgb_rios", "eixo": "saneamento", "nome": "SGB/CPRM — Rios (BC250)",
     "protocolo": "wfs", "endpoint": "https://opendata.sgb.gov.br/geoserver/ows",
     "type_name": "p3m:vw_ibge_rios", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "sgb_bacias", "eixo": "saneamento", "nome": "SGB/CPRM — Bacias hidrograficas",
     "protocolo": "wfs", "endpoint": "https://opendata.sgb.gov.br/geoserver/ows",
     "type_name": "p3m:vw_ibge_bacia_hidro_6", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bc250_drenagem", "eixo": "saneamento", "nome": "IBGE — BC250 Trechos de drenagem",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CCAR:BC250_2025_hid_trecho_drenagem_l", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bc250_massa_dagua", "eixo": "saneamento", "nome": "IBGE — BC250 Massa d'agua",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CCAR:BC250_2025_hid_massa_dagua_a", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "sgb_pocos_siagas", "eixo": "saneamento", "nome": "SGB/CPRM — Pocos (SIAGAS)",
     "protocolo": "wfs", "endpoint": "https://opendata.sgb.gov.br/geoserver/ows",
     "type_name": "hidrologia:pocos_siagas", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    # --- Eixo 4: Ambiental ---
    {"id": "sicar_imoveis", "eixo": "ambiental", "nome": "SICAR — Imoveis (CAR)",
     "protocolo": "wfs", "endpoint": "https://geoserver.car.gov.br/geoserver/sicar/wfs",
     "type_name": "sicar:sicar_imoveis_{uf}", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_codigo", "campo": "cod_municipio_ibge"}, "licenca": "Publica"},
    {"id": "icmbio_embargos", "eixo": "ambiental", "nome": "ICMBio — Embargos",
     "protocolo": "wfs", "endpoint": "https://geoservicos.inde.gov.br/geoserver/ICMBio/ows",
     "type_name": "ICMBio:embargos_icmbio", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_nome", "campo": "municipio"}, "licenca": "Publica"},
    {"id": "icmbio_uc", "eixo": "ambiental", "nome": "ICMBio — UCs federais",
     "protocolo": "wfs", "endpoint": "https://geoservicos.inde.gov.br/geoserver/ICMBio/ows",
     "type_name": "ICMBio:limiteucsfederais_a", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "sgb_risco", "eixo": "ambiental", "nome": "SGB/CPRM — Risco geologico",
     "protocolo": "wfs", "endpoint": "https://opendata.sgb.gov.br/geoserver/ows",
     "type_name": "gestao-territorial:risco_geologico", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "anm_sigmine", "eixo": "ambiental", "nome": "ANM/SIGMINE — Processos minerarios",
     "protocolo": "arcgis",
     "endpoint": "https://geo.anm.gov.br/arcgis/rest/services/SIGMINE/dados_anm/MapServer",
     "layer_id": "0", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "anm_sigmine_req_pesquisa", "eixo": "ambiental",
     "nome": "ANM/SIGMINE — Requerimento de pesquisa",
     "protocolo": "zip_remoto", "subset": "FASE = 'REQUERIMENTO DE PESQUISA'",
     "srs": "EPSG:4674", "filtro": {"tipo": "bbox"}, "licenca": "Publica",
     "origem_url": "https://app.anm.gov.br/",
     "indisponivel": "Host app.anm.gov.br indisponível (connection timed out)"},
    {"id": "anm_sigmine_licenciamento", "eixo": "ambiental",
     "nome": "ANM/SIGMINE — Licenciamento",
     "protocolo": "zip_remoto", "subset": "FASE = 'LICENCIAMENTO'",
     "srs": "EPSG:4674", "filtro": {"tipo": "bbox"}, "licenca": "Publica",
     "origem_url": "https://app.anm.gov.br/",
     "indisponivel": "Host app.anm.gov.br indisponível (connection timed out)"},
    {"id": "anm_sigmine_concessao_lavra", "eixo": "ambiental",
     "nome": "ANM/SIGMINE — Concessao de lavra",
     "protocolo": "zip_remoto", "subset": "FASE = 'CONCESSÃO DE LAVRA'",
     "srs": "EPSG:4674", "filtro": {"tipo": "bbox"}, "licenca": "Publica",
     "origem_url": "https://app.anm.gov.br/",
     "indisponivel": "Host app.anm.gov.br indisponível (connection timed out)"},
    {"id": "anm_sigmine_lavra_garimpeira", "eixo": "ambiental",
     "nome": "ANM/SIGMINE — Lavra garimpeira",
     "protocolo": "zip_remoto", "subset": "FASE = 'LAVRA GARIMPEIRA'",
     "srs": "EPSG:4674", "filtro": {"tipo": "bbox"}, "licenca": "Publica",
     "origem_url": "https://app.anm.gov.br/",
     "indisponivel": "Host app.anm.gov.br indisponível (connection timed out)"},
    {"id": "ibge_bdia_pedologia", "eixo": "ambiental", "nome": "IBGE/BDIA — Pedologia",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "BDIA:pedo_area", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bdia_geologia", "eixo": "ambiental", "nome": "IBGE/BDIA — Geologia",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "BDIA:geol_area", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bdia_geomorfologia", "eixo": "ambiental", "nome": "IBGE/BDIA — Geomorfologia",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "BDIA:geom_area", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibge_bdia_vegetacao", "eixo": "ambiental", "nome": "IBGE/BDIA — Vegetacao",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "BDIA:vege_area", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "mapbiomas_cobertura", "eixo": "ambiental",
     "nome": "MapBiomas — Cobertura e uso da terra (Coleção 9)",
     "protocolo": "raster_cog",
     "url_template": "https://storage.googleapis.com/mapbiomas-public/initiatives/brasil/collection_9/lclu/coverage/brasil_coverage_{ano}.tif",
     "srs": "EPSG:4326", "filtro": {"tipo": "bbox"},
     "ano_default": 2023, "anos": list(range(1985, 2024)),
     "licenca": "CC-BY-SA"},
    # --- Eixo 7: Urbano ---
    {"id": "ibge_areas_urbanizadas", "eixo": "urbano", "nome": "IBGE — Areas urbanizadas (2019)",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CGEO:AU_2022_AreasUrbanizadas2019_Municipios", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_codigo", "campo": "cd_mun"}, "licenca": "Publica"},
    {"id": "ibge_aglomerados_subnormais", "eixo": "urbano",
     "nome": "IBGE — Aglomerados subnormais (2010)",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CGEO:AglomeradosSubnormais2010_Limites", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_codigo", "campo": "cd_geocodm"}, "licenca": "Publica"},
    {"id": "ibge_bc250_area_densa", "eixo": "urbano",
     "nome": "IBGE — BC250 Area densamente edificada",
     "protocolo": "wfs", "endpoint": "https://geoservicos.ibge.gov.br/geoserver/ows",
     "type_name": "CCAR:BC250_2025_lml_area_densamente_edificada_a", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "osm_pois", "eixo": "urbano", "nome": "OSM — POIs (equipamentos e edificações, Overpass)",
     "protocolo": "osm", "licenca": "OpenStreetMap contributors"},
    # --- Eixo 8: Politico-administrativo (download manual) ---
    # SIGEF nao tem endpoint publico: export_shp.py exige login gov.br
    # (medição em docs/diagnostico-plano-diretor/incra-sigef-acesso.md).
    {"id": "incra_sigef_parcelas", "eixo": "pol-admin",
     "nome": "INCRA/SIGEF — Parcelas certificadas (download manual)",
     "protocolo": "arquivo", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica (exige login gov.br)",
     "arquivo_glob": ["*sigef*.zip", "*parcela*certific*.zip",
                      "*sigef*.shp", "*sigef*.gpkg"],
     "origem_url": "https://certificacao.incra.gov.br/csv_shp/export_shp.py",
     "requer_login": "gov.br"},
    # --- ArcGIS REST (Fase C) ---
    {"id": "ana_hidrografia", "eixo": "saneamento", "nome": "ANA — Hidrografia",
     "protocolo": "arcgis",
     "endpoint": "https://www.snirh.gov.br/arcgis/rest/services/DADOSABERTOS/Hidrografia/MapServer",
     "layer_id": "0", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibama_autos", "eixo": "ambiental", "nome": "IBAMA — Autos de infracao/embargos",
     "protocolo": "arcgis",
     "endpoint": "https://pamgia.ibama.gov.br/server/rest/services/app_dadosabertos/adm_auto_infracao_p/MapServer",
     "layer_id": "0", "srs": "EPSG:4674",
     "filtro": {"tipo": "cql_codigo", "campo": "cod_municipio"}, "licenca": "Publica"},
    {"id": "ibama_esgoto", "eixo": "saneamento", "nome": "IBAMA — Esgotamento sanitario",
     "protocolo": "arcgis",
     "endpoint": "https://pamgia.ibama.gov.br/server/rest/services/SIGAGEO/Sistema_de_Esgotamento_Sanit%C3%A1rio/MapServer",
     "layer_id": "6", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibama_agua", "eixo": "saneamento", "nome": "IBAMA — Abastecimento de agua",
     "protocolo": "arcgis",
     "endpoint": "https://pamgia.ibama.gov.br/server/rest/services/SIGAGEO/Sistema_de_Abastecimento_de_%C3%81gua/MapServer",
     "layer_id": "5", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    {"id": "ibama_aterro", "eixo": "saneamento", "nome": "IBAMA — Aterro sanitario",
     "protocolo": "arcgis",
     "endpoint": "https://pamgia.ibama.gov.br/server/rest/services/SIGAGEO/Aterro_Sanit%C3%A1rio/MapServer",
     "layer_id": "8", "srs": "EPSG:4674",
     "filtro": {"tipo": "bbox"}, "licenca": "Publica"},
    # --- geobr v1 (GPKG; sem dependencia externa) ---
    {"id": "geobr_municipio", "eixo": "demografia", "nome": "Limite municipal (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_municipality", "recorte": "code"},
    {"id": "geobr_setores", "eixo": "demografia", "nome": "Setores censitarios (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_census_tract", "recorte": "code"},
    {"id": "geobr_ponderacao", "eixo": "demografia", "nome": "Areas de ponderacao (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_weighting_area", "recorte": "code"},
    {"id": "geobr_escolas", "eixo": "educacao", "nome": "Escolas (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_schools", "recorte": "bbox"},
    {"id": "geobr_saude", "eixo": "saude", "nome": "Estabelecimentos de saude (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_health_facilities", "recorte": "bbox"},
    {"id": "geobr_biomas", "eixo": "ambiental", "nome": "Biomas (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_biomes", "recorte": "bbox"},
    {"id": "geobr_ucs", "eixo": "ambiental", "nome": "Unidades de conservacao (geobr)",
     "protocolo": "geobr", "algo": "read_conservation_units", "recorte": "bbox"},
    {"id": "geobr_terras_indigenas", "eixo": "ambiental", "nome": "Terras indigenas (geobr)",
     "protocolo": "geobr", "algo": "read_indigenous_land", "recorte": "bbox"},
    {"id": "geobr_risco", "eixo": "ambiental", "nome": "Areas de risco de desastre (geobr)",
     "protocolo": "geobr", "algo": "read_disaster_risk_area", "recorte": "bbox"},
    {"id": "geobr_mancha_urbana", "eixo": "urbano", "nome": "Mancha urbana (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_urban_area", "recorte": "bbox"},
    {"id": "geobr_sede", "eixo": "pol-admin", "nome": "Sede municipal (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_municipal_seat", "recorte": "bbox"},
    {"id": "geobr_bairros", "eixo": "pol-admin", "nome": "Bairros (IBGE/geobr)",
     "protocolo": "geobr", "algo": "read_neighborhood", "recorte": "bbox"},
    # --- geobr v2 (so-v2; REQUEREM driver Parquet ou pyarrow; senao sao pulados) ---
    {"id": "geobr_favelas", "eixo": "demografia", "nome": "Favelas/comunidades (geobr v2)",
     "protocolo": "geobr", "algo": "read_favela_v2", "recorte": "code", "requer_parquet": True},
    {"id": "geobr_locais_votacao", "eixo": "pol-admin", "nome": "Locais de votacao (geobr v2)",
     "protocolo": "geobr", "algo": "read_polling_places_v2", "recorte": "code", "requer_parquet": True},
    {"id": "geobr_quilombolas", "eixo": "ambiental", "nome": "Terras quilombolas (geobr v2)",
     "protocolo": "geobr", "algo": "read_quilombola_land_v2", "recorte": "bbox", "requer_parquet": True},
    # --- Eixo 9: Agropecuária (IBGE Agregados v3) ---
    {"id": "ibge_pam_temporarias", "eixo": "agropecuaria",
     "nome": "IBGE — PAM Lavouras temporárias",
     "protocolo": "ibge_tabular", "agregado": 1612,
     "variaveis": ["109", "216", "214", "112", "215"],
     "classificacao": {"81": "all"}, "periodo_default": "-1",
     "licenca": "Publica"},
    {"id": "ibge_pam_permanentes", "eixo": "agropecuaria",
     "nome": "IBGE — PAM Lavouras permanentes",
     "protocolo": "ibge_tabular", "agregado": 1613,
     "variaveis": ["2313", "216", "214", "112", "215"],
     "classificacao": {"82": "all"}, "periodo_default": "-1",
     "licenca": "Publica"},
    {"id": "ibge_censo_agro", "eixo": "agropecuaria",
     "nome": "IBGE — Censo Agropecuário 2017",
     "protocolo": "ibge_tabular", "agregado": 6881,
     "variaveis": ["9587", "184"],
     "classificacao": {"222": "all"}, "periodo_default": "2017",
     "licenca": "Publica"},
    # --- Contexto ---
    {"id": "basemap_satelite", "eixo": "contexto", "nome": "Imagem de satelite (Esri)",
     "protocolo": "basemap"},
]
